"""
Python 2.7.10

Euler Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
"""

def even_fib_nums():
  a, b = 0, 1
  sum_evens = 0
  while b <= 4000000:
    a, b = b, a + b
    if b % 2 == 0:
      sum_evens += b
  return sum_evens

print even_fib_nums()